services:
    backend:
        build:
            dockerfile: ./Dockerfile-backend-build
        # ports:
        #     - "8080:8080"
        depends_on:
            - mysql
        restart: always
        environment:
            spring.profiles.active: dev
            spring.datasource.druid.url: jdbc:mysql://mysql:3306/${DB_NAME:-umpoint}?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
            spring.datasource.druid.username: ${DB_USERNAME:-umpoint}
            spring.datasource.druid.password: ${DB_PASSWORD:-umpoint}
            spring.ai.azure.openai.api-key: ${AZURE_GPT_API_KEY?Azure GPT API Key not set}
            azure.storage.connection-string: ${AZURE_STORAGE_CONNECTION_STRING?Azure Storage Key not set}
        networks:
            - umpoint-network

    # frontend-admin:
    #     build:
    #         context: ./umpoint/umpoint-admin
    #         dockerfile: ./Dockerfile
    #     ports:
    #         - "8001:8001"
    #     restart: always
    #     environment:
    #         VITE_APP_API: ${DEPLOY_DOMAIN}/api
    #     networks:
    #         - umpoint-network

    frontend-admin:
        image: chunhong717/umpoint-admin:latest
        # ports:
        #     - "8001:8001"
        #     - "8002:80"
        environment:
            VITE_APP_API: ${DEPLOY_DOMAIN}/api
        restart: always
        networks:
            - umpoint-network

    frontend-user:
        build:
            context: ./umpoint/umpoint-frontend
            dockerfile: ./Dockerfile.prod
            args:
                VITE_BOOKING_API_URL: ${DEPLOY_DOMAIN}/api
                VITE_BASE_URL: ${DEPLOY_DOMAIN}/user/
        # ports:
        #     - "5173:5173"
        environment:
            VITE_BOOKING_API_URL: ${DEPLOY_DOMAIN}/api
            VITE_BASE_URL: ${DEPLOY_DOMAIN}/user/
        command: [nginx-debug, "-g", "daemon off;"]
        networks:
            - umpoint-network

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password1234
            MYSQL_DATABASE: ${DB_NAME:-umpoint}
            MYSQL_USER: ${DB_USERNAME:-umpoint}
            MYSQL_PASSWORD: ${DB_PASSWORD:-umpoint}
        # ports:
        #     - "23306:3306"
        restart: always
        volumes:
            - umpoint-mysql:/var/lib/mysql # persistent volume
            - ./sql-script:/docker-entrypoint-initdb.d # init scripts
        networks:
            - umpoint-network

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "56789:80"
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password1234
            MYSQL_USER: ${DB_USERNAME:-umpoint}
            MYSQL_PASSWORD: ${DB_PASSWORD:-umpoint}
        networks:
            - umpoint-network

    nginx:
        image: nginx:1.27
        ports:
            - "1234:80"
        volumes:
            - ./nginx/localbuild-global-nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend-admin
            - frontend-user
        restart: always
        command: [nginx-debug, "-g", "daemon off;"]
        networks:
            - umpoint-network

volumes:
    umpoint-mysql:


networks:
    umpoint-network:
